{"name": "test_usuario_incorrecto", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x00000200423EEC10>\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"3ae5886a-798b-46b3-b8e4-03f896bc3661\")>\n\n    @pytest.mark.regression\n    def test_usuario_incorrecto(self, driver):\n        username = \"hola\"\n        password = os.getenv(\"PASSWORD_CAP\")\n>       home_screen = HomeScreen(driver)\nE       TypeError: 'module' object is not callable\n\ntests\\test_login.py:28: TypeError"}, "start": 1677596353298, "stop": 1677596353298, "uuid": "fd90622d-7db1-47d2-b83a-6efbe190e3f0", "historyId": "be4815435cb90c14eb1f044548429599", "testCaseId": "b2b0ea8429bd09002f0ae8b92d7b9a6e", "fullName": "tests.test_login.TestLogin#test_usuario_incorrecto", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "GS1726967D01LP"}, {"name": "thread", "value": "25480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}