{"name": "test_usuario_incorrecto", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x000001F21164C5D0>\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"d02b5b38-187a-4752-8366-f1c08467c1f9\")>\n\n    @pytest.mark.regression\n    def test_usuario_incorrecto(self, driver):\n        username = \"hola\"\n        password = os.getenv(\"PASSWORD_CAP\")\n>       home_screen = HomeScreen(driver)\nE       TypeError: 'module' object is not callable\n\ntests\\test_login.py:28: TypeError"}, "start": 1677596288141, "stop": 1677596288141, "uuid": "62a6ac68-3d6f-47c4-a090-316c89cf3ea5", "historyId": "be4815435cb90c14eb1f044548429599", "testCaseId": "b2b0ea8429bd09002f0ae8b92d7b9a6e", "fullName": "tests.test_login.TestLogin#test_usuario_incorrecto", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "GS1726967D01LP"}, {"name": "thread", "value": "23456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}