{"name": "test_contraseña_incorrecta", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x000002004242CBD0>\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"bfea324c-1dba-4f49-8a5f-b5fc343e95ce\")>\n\n    @pytest.mark.smoketest\n    def test_contraseña_incorrecta(self, driver):\n        username = os.getenv(\"USERNAME_CAP\")\n        password = \"prueba\"\n>       home_screen = HomeScreen(driver)\nE       TypeError: 'module' object is not callable\n\ntests\\test_login.py:39: TypeError"}, "start": 1677596365728, "stop": 1677596365729, "uuid": "4d5dcb9f-da0f-4e73-aac2-7f37742e0563", "historyId": "df24dea16fa9d8256fcababb700b27d5", "testCaseId": "888ee164850eb955d2944949db111236", "fullName": "tests.test_login.TestLogin#test_contraseña_incorrecta", "labels": [{"name": "tag", "value": "smoketest"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "GS1726967D01LP"}, {"name": "thread", "value": "25480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}